# TypeProf 0.12.0

# Classes
module GruubyMix
  class Member
    @heart: Integer
    @technique: Integer
    @physical: Integer

    def initialize: (Integer heart, Integer technique, Integer physical) -> void
    def total: (?rate: Integer) -> Integer
  end
end
